files = [
    'stream/tayspridemerch_male_p.rpf/*',
    'stream/tayspridemerch_male.rpf/*',
    'stream/tayspridemerch_female_p.rpf/*',
    'stream/tayspridemerch_female.rpf/*',
    'stream/creaturemetadata.rpf/*'
]

[meta]
'stream/mp_m_freemode_01_mp_m_tayspridepack.meta' = 'SHOP_PED_APPAREL_META_FILE'
'stream/mp_f_freemode_01_mp_f_tayspridepack.meta' = 'SHOP_PED_APPAREL_META_FILE'
'stream/pedalternatevariations.meta' = 'ALTERNATE_VARIATIONS_FILE'